const vscode = require('vscode');
const HTTPSupport = require('axios');
const Cookies = require('tough-cookie');
const MarkdownIt = require('markdown-it');
const MarkdownItKatex = require('@luogu-dev/markdown-it-katex');
const md=MarkdownIt();
md.use(MarkdownItKatex);//Markdown-it-Latex无法使用
function jsonarraylength(jsonarray) {
	var jsonlen=0;
	for(var i in jsonarray){
		jsonlen++;
		console.log(i);
	}
	console.log(jsonlen);
	return jsonlen;
}
function MakeTag(array,length) {
	var str='';
	for(var i=0;i<length-1;i++){
		str+=array[i].Name+'、';
	}
	str+=array[length-1].Name;
	return str;
}
function MakeSample(array,length){
	if(length==0)return '没有样例哦！';
	var str='';
	for(var i=0;i<length;i++){
		str+=`
		<h5>Sample #${String(i+1)}</h5>
		<b>Input:</b>
		<p>${array[i][0]}</p>
		<b>Output:</b>
		<p>${array[i][1]}</p>

		`
	}
	console.log(str);
	return str;
}
const jar=new Cookies.CookieJar();
const APILOAD = HTTPSupport.default.create({
	"baseURL": 'https://www.luogu.com.cn/',
	"timeout": 10000,
	"withCredentials": true,
	jar
})
/**
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
	console.log('ACTIVE');
	let disposable = vscode.commands.registerCommand('extension.About', function () {
		vscode.window.showInformationMessage('LVSC Version 1.0.0 Beta');//关于我们
	});
	context.subscriptions.push(disposable);
	disposable = vscode.commands.registerCommand('extension.WatchProblem', async function () {
		console.log('Watch Problem');
		const PID=await vscode.window.showInputBox({
			placeHolder: 'Input the Problem ID',
			ignoreFocusOut: true
		}).then(
			function returnPID(MSG) {
				return MSG;
			}
		);
		if(!PID){
			return;//用户没有输入
		}
		console.log('PID:'+PID);
		const json=await APILOAD.get('api/problem/detail/'+PID).then(
			function returnJSON(MSG) {
				return MSG;
			}
		);//读入题目JSON
		console.log(json.data);
		if(json.data.status==200){
			vscode.window.showInformationMessage('Get Problem Successfully!');
			const TagsArrayLength=jsonarraylength(json.data.data.Tags);
			const Tags=MakeTag(json.data.data.Tags,TagsArrayLength);
			console.log(Tags);
			//生成HTML文件展示
			console.log(jsonarraylength(json.data.data.Sample));
			var BG='',miaoshu='';
			const sample=MakeSample(json.data.data.Sample,jsonarraylength(json.data.data.Sample));
			if(!json.data.data.Background){
				BG='无题目背景';
			}
			else{
				BG=json.data.data.Background;
			}
			console.log(BG);
			if(!json.data.data.Description){
				miaoshu='无题目描述';
			}
			else{
				miaoshu=json.data.data.Description;
			}
			var Hint='';
			if(!json.data.data.Hint){
				Hint='无题目提示';
			}
			else{
				miaoshu=json.data.data.Hint;
			}
			console.log(sample);
			const HTML=`
			<!DOCTYPE HTML>
			<html lang="en">
				<head>
					<meta charset="UTF-8">
					<title>${json.data.data.StringPID+':'+json.data.data.Name}</title>
					<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.12.0/build/styles/default.min.css">
					<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css">
				</head>
				<body>
					<h1>${json.data.data.StringPID+':'+json.data.data.Name}</h1>
					<hr>
					<h2>题目背景</h2>
					${md.render(BG)}
					<h2>题目描述</h2>
					${md.render(miaoshu)}
					<h2>输入格式</h2>
					${md.render(json.data.data.InputFormat)}
					<h2>输出格式</h2>
					${md.render(json.data.data.OutputFormat)}
					<h2>样例</h2>
					${sample}
					<h2>提示</h2>
					${md.render(Hint)}
					<h2>标签</h2>
					<b>${Tags}</b>
					<p>  </p>
					<b>题目来源于洛谷。<br><br><br><br>Generated By LVSC. Copyright 2019-2020 © Chuangzhi Programming Studio. All Right Reserved.</b>
				</body>	
			</html>	
			`
			console.log(HTML);
			const panel=vscode.window.createWebviewPanel(json.data.data.StringPID+':'+json.data.data.Name,
			json.data.data.StringPID+':'+json.data.data.Name,vscode.ViewColumn.Two,{
				enableScripts: true,
				retainContextWhenHidden: true
			})
			panel.webview.html=HTML;
		}
		else{
			vscode.window.showErrorMessage('Get Problem Failed, Error Code:'+String(json.data.status)+" Reason:"+json.data.data);
			//JSON错误，可能无权看题、没有这道题等等
		}
	});
	context.subscriptions.push(disposable);
}
exports.activate = activate;
function deactivate() {}
module.exports = {
	activate,
	deactivate
}
